import 'quran_service.dart';

class QuranScreenData {
  static const List<QuranSurah> surahs = [
    QuranSurah(
        number: 1,
        nameArabic: "الفاتحة",
        nameKurdish: "فاتیحە",
        ayahCount: 7,
        isMakki: true,
        juzStart: 1),
    QuranSurah(
        number: 2,
        nameArabic: "البقرة",
        nameKurdish: "بەقەرە",
        ayahCount: 286,
        isMakki: false,
        juzStart: 1),
    QuranSurah(
        number: 3,
        nameArabic: "آل عمران",
        nameKurdish: "ئالی عیمران",
        ayahCount: 200,
        isMakki: false,
        juzStart: 3),
    QuranSurah(
        number: 4,
        nameArabic: "النساء",
        nameKurdish: "نیساء",
        ayahCount: 176,
        isMakki: false,
        juzStart: 4),
    QuranSurah(
        number: 5,
        nameArabic: "المائدة",
        nameKurdish: "مائیدە",
        ayahCount: 120,
        isMakki: false,
        juzStart: 6),
    QuranSurah(
        number: 6,
        nameArabic: "الأنعام",
        nameKurdish: "ئەنعام",
        ayahCount: 165,
        isMakki: true,
        juzStart: 7),
    QuranSurah(
        number: 7,
        nameArabic: "الأعراف",
        nameKurdish: "ئەعراف",
        ayahCount: 206,
        isMakki: true,
        juzStart: 8),
    QuranSurah(
        number: 8,
        nameArabic: "الأنفال",
        nameKurdish: "ئەنفال",
        ayahCount: 75,
        isMakki: false,
        juzStart: 9),
    QuranSurah(
        number: 9,
        nameArabic: "التوبة",
        nameKurdish: "تەوبە",
        ayahCount: 129,
        isMakki: false,
        juzStart: 10),
    QuranSurah(
        number: 10,
        nameArabic: "يونس",
        nameKurdish: "یونس",
        ayahCount: 109,
        isMakki: true,
        juzStart: 11),
    QuranSurah(
        number: 11,
        nameArabic: "هود",
        nameKurdish: "هوود",
        ayahCount: 123,
        isMakki: true,
        juzStart: 11),
    QuranSurah(
        number: 12,
        nameArabic: "يوسف",
        nameKurdish: "یوسف",
        ayahCount: 111,
        isMakki: true,
        juzStart: 12),
    QuranSurah(
        number: 13,
        nameArabic: "الرعد",
        nameKurdish: "ڕەعد",
        ayahCount: 43,
        isMakki: false,
        juzStart: 13),
    QuranSurah(
        number: 14,
        nameArabic: "إبراهيم",
        nameKurdish: "ئیبراهیم",
        ayahCount: 52,
        isMakki: true,
        juzStart: 13),
    QuranSurah(
        number: 15,
        nameArabic: "الحجر",
        nameKurdish: "حیجر",
        ayahCount: 99,
        isMakki: true,
        juzStart: 14),
    QuranSurah(
        number: 16,
        nameArabic: "النحل",
        nameKurdish: "نەحل",
        ayahCount: 128,
        isMakki: true,
        juzStart: 14),
    QuranSurah(
        number: 17,
        nameArabic: "الإسراء",
        nameKurdish: "ئیسراء",
        ayahCount: 111,
        isMakki: true,
        juzStart: 15),
    QuranSurah(
        number: 18,
        nameArabic: "الكهف",
        nameKurdish: "کەهف",
        ayahCount: 110,
        isMakki: true,
        juzStart: 15),
    QuranSurah(
        number: 19,
        nameArabic: "مريم",
        nameKurdish: "مەریەم",
        ayahCount: 98,
        isMakki: true,
        juzStart: 16),
    QuranSurah(
        number: 20,
        nameArabic: "طه",
        nameKurdish: "تاها",
        ayahCount: 135,
        isMakki: true,
        juzStart: 16),
    QuranSurah(
        number: 21,
        nameArabic: "الأنبياء",
        nameKurdish: "ئەنبیاء",
        ayahCount: 112,
        isMakki: true,
        juzStart: 17),
    QuranSurah(
        number: 22,
        nameArabic: "الحج",
        nameKurdish: "حەج",
        ayahCount: 78,
        isMakki: false,
        juzStart: 17),
    QuranSurah(
        number: 23,
        nameArabic: "المؤمنون",
        nameKurdish: "مۆمینون",
        ayahCount: 118,
        isMakki: true,
        juzStart: 18),
    QuranSurah(
        number: 24,
        nameArabic: "النور",
        nameKurdish: "نوور",
        ayahCount: 64,
        isMakki: false,
        juzStart: 18),
    QuranSurah(
        number: 25,
        nameArabic: "الفرقان",
        nameKurdish: "فورقان",
        ayahCount: 77,
        isMakki: true,
        juzStart: 18),
    QuranSurah(
        number: 26,
        nameArabic: "الشعراء",
        nameKurdish: "شوعەراء",
        ayahCount: 227,
        isMakki: true,
        juzStart: 19),
    QuranSurah(
        number: 27,
        nameArabic: "النمل",
        nameKurdish: "نەمل",
        ayahCount: 93,
        isMakki: true,
        juzStart: 19),
    QuranSurah(
        number: 28,
        nameArabic: "القصص",
        nameKurdish: "قەسەس",
        ayahCount: 88,
        isMakki: true,
        juzStart: 20),
    QuranSurah(
        number: 29,
        nameArabic: "العنكبوت",
        nameKurdish: "عەنکەبووت",
        ayahCount: 69,
        isMakki: true,
        juzStart: 20),
    QuranSurah(
        number: 30,
        nameArabic: "الروم",
        nameKurdish: "ڕووم",
        ayahCount: 60,
        isMakki: true,
        juzStart: 21),
    QuranSurah(
        number: 31,
        nameArabic: "لقمان",
        nameKurdish: "لوقمان",
        ayahCount: 34,
        isMakki: true,
        juzStart: 21),
    QuranSurah(
        number: 32,
        nameArabic: "السجدة",
        nameKurdish: "سەجدە",
        ayahCount: 30,
        isMakki: true,
        juzStart: 21),
    QuranSurah(
        number: 33,
        nameArabic: "الأحزاب",
        nameKurdish: "ئەحزاب",
        ayahCount: 73,
        isMakki: false,
        juzStart: 21),
    QuranSurah(
        number: 34,
        nameArabic: "سبأ",
        nameKurdish: "سەبأ",
        ayahCount: 54,
        isMakki: true,
        juzStart: 22),
    QuranSurah(
        number: 35,
        nameArabic: "فاطر",
        nameKurdish: "فاتیر",
        ayahCount: 45,
        isMakki: true,
        juzStart: 22),
    QuranSurah(
        number: 36,
        nameArabic: "يس",
        nameKurdish: "یاسین",
        ayahCount: 83,
        isMakki: true,
        juzStart: 22),
    QuranSurah(
        number: 37,
        nameArabic: "الصافات",
        nameKurdish: "سافات",
        ayahCount: 182,
        isMakki: true,
        juzStart: 23),
    QuranSurah(
        number: 38,
        nameArabic: "ص",
        nameKurdish: "ساد",
        ayahCount: 88,
        isMakki: true,
        juzStart: 23),
    QuranSurah(
        number: 39,
        nameArabic: "الزمر",
        nameKurdish: "زومەر",
        ayahCount: 75,
        isMakki: true,
        juzStart: 23),
    QuranSurah(
        number: 40,
        nameArabic: "غافر",
        nameKurdish: "غافیر",
        ayahCount: 85,
        isMakki: true,
        juzStart: 24),
    QuranSurah(
        number: 41,
        nameArabic: "فصلت",
        nameKurdish: "فوسیلەت",
        ayahCount: 54,
        isMakki: true,
        juzStart: 24),
    QuranSurah(
        number: 42,
        nameArabic: "الشورى",
        nameKurdish: "شووری",
        ayahCount: 53,
        isMakki: true,
        juzStart: 25),
    QuranSurah(
        number: 43,
        nameArabic: "الزخرف",
        nameKurdish: "زوخروف",
        ayahCount: 89,
        isMakki: true,
        juzStart: 25),
    QuranSurah(
        number: 44,
        nameArabic: "الدخان",
        nameKurdish: "دوخان",
        ayahCount: 59,
        isMakki: true,
        juzStart: 25),
    QuranSurah(
        number: 45,
        nameArabic: "الجاثية",
        nameKurdish: "جاسیە",
        ayahCount: 37,
        isMakki: true,
        juzStart: 25),
    QuranSurah(
        number: 46,
        nameArabic: "الأحقاف",
        nameKurdish: "ئەحقاف",
        ayahCount: 35,
        isMakki: true,
        juzStart: 26),
    QuranSurah(
        number: 47,
        nameArabic: "محمد",
        nameKurdish: "محەممەد",
        ayahCount: 38,
        isMakki: false,
        juzStart: 26),
    QuranSurah(
        number: 48,
        nameArabic: "الفتح",
        nameKurdish: "فەتح",
        ayahCount: 29,
        isMakki: false,
        juzStart: 26),
    QuranSurah(
        number: 49,
        nameArabic: "الحجرات",
        nameKurdish: "حوجورات",
        ayahCount: 18,
        isMakki: false,
        juzStart: 26),
    QuranSurah(
        number: 50,
        nameArabic: "ق",
        nameKurdish: "قاف",
        ayahCount: 45,
        isMakki: true,
        juzStart: 26),
    QuranSurah(
        number: 51,
        nameArabic: "الذاريات",
        nameKurdish: "زاریات",
        ayahCount: 60,
        isMakki: true,
        juzStart: 26),
    QuranSurah(
        number: 52,
        nameArabic: "الطور",
        nameKurdish: "تور",
        ayahCount: 49,
        isMakki: true,
        juzStart: 27),
    QuranSurah(
        number: 53,
        nameArabic: "النجم",
        nameKurdish: "نەجم",
        ayahCount: 62,
        isMakki: true,
        juzStart: 27),
    QuranSurah(
        number: 54,
        nameArabic: "القمر",
        nameKurdish: "قەمەر",
        ayahCount: 55,
        isMakki: true,
        juzStart: 27),
    QuranSurah(
        number: 55,
        nameArabic: "الرحمن",
        nameKurdish: "ڕەحمان",
        ayahCount: 78,
        isMakki: false,
        juzStart: 27),
    QuranSurah(
        number: 56,
        nameArabic: "الواقعة",
        nameKurdish: "واقیعە",
        ayahCount: 96,
        isMakki: true,
        juzStart: 27),
    QuranSurah(
        number: 57,
        nameArabic: "الحديد",
        nameKurdish: "حەدید",
        ayahCount: 29,
        isMakki: false,
        juzStart: 27),
    QuranSurah(
        number: 58,
        nameArabic: "المجادلة",
        nameKurdish: "موجادیلە",
        ayahCount: 22,
        isMakki: false,
        juzStart: 28),
    QuranSurah(
        number: 59,
        nameArabic: "الحشر",
        nameKurdish: "حەشر",
        ayahCount: 24,
        isMakki: false,
        juzStart: 28),
    QuranSurah(
        number: 60,
        nameArabic: "الممتحنة",
        nameKurdish: "مومتەحینە",
        ayahCount: 13,
        isMakki: false,
        juzStart: 28),
    QuranSurah(
        number: 61,
        nameArabic: "الصف",
        nameKurdish: "سەف",
        ayahCount: 14,
        isMakki: false,
        juzStart: 28),
    QuranSurah(
        number: 62,
        nameArabic: "الجمعة",
        nameKurdish: "جومعە",
        ayahCount: 11,
        isMakki: false,
        juzStart: 28),
    QuranSurah(
        number: 63,
        nameArabic: "المنافقون",
        nameKurdish: "موناافیقون",
        ayahCount: 11,
        isMakki: false,
        juzStart: 28),
    QuranSurah(
        number: 64,
        nameArabic: "التغابن",
        nameKurdish: "تەغابون",
        ayahCount: 18,
        isMakki: false,
        juzStart: 28),
    QuranSurah(
        number: 65,
        nameArabic: "الطلاق",
        nameKurdish: "تەلاق",
        ayahCount: 12,
        isMakki: false,
        juzStart: 28),
    QuranSurah(
        number: 66,
        nameArabic: "التحريم",
        nameKurdish: "تەحریم",
        ayahCount: 12,
        isMakki: false,
        juzStart: 28),
    QuranSurah(
        number: 67,
        nameArabic: "الملك",
        nameKurdish: "مولک",
        ayahCount: 30,
        isMakki: true,
        juzStart: 29),
    QuranSurah(
        number: 68,
        nameArabic: "القلم",
        nameKurdish: "قەلەم",
        ayahCount: 52,
        isMakki: true,
        juzStart: 29),
    QuranSurah(
        number: 69,
        nameArabic: "الحاقة",
        nameKurdish: "حاقە",
        ayahCount: 52,
        isMakki: true,
        juzStart: 29),
    QuranSurah(
        number: 70,
        nameArabic: "المعارج",
        nameKurdish: "مەعاریج",
        ayahCount: 44,
        isMakki: true,
        juzStart: 29),
    QuranSurah(
        number: 71,
        nameArabic: "نوح",
        nameKurdish: "نووح",
        ayahCount: 28,
        isMakki: true,
        juzStart: 29),
    QuranSurah(
        number: 72,
        nameArabic: "الجن",
        nameKurdish: "جین",
        ayahCount: 28,
        isMakki: true,
        juzStart: 29),
    QuranSurah(
        number: 73,
        nameArabic: "المزمل",
        nameKurdish: "موزەممیل",
        ayahCount: 20,
        isMakki: true,
        juzStart: 29),
    QuranSurah(
        number: 74,
        nameArabic: "المدثر",
        nameKurdish: "موددەسیر",
        ayahCount: 56,
        isMakki: true,
        juzStart: 29),
    QuranSurah(
        number: 75,
        nameArabic: "القيامة",
        nameKurdish: "قیامەت",
        ayahCount: 40,
        isMakki: true,
        juzStart: 29),
    QuranSurah(
        number: 76,
        nameArabic: "الإنسان",
        nameKurdish: "ئینسان",
        ayahCount: 31,
        isMakki: false,
        juzStart: 29),
    QuranSurah(
        number: 77,
        nameArabic: "المرسلات",
        nameKurdish: "مورسەلات",
        ayahCount: 50,
        isMakki: true,
        juzStart: 29),
    QuranSurah(
        number: 78,
        nameArabic: "النبأ",
        nameKurdish: "نەبأ",
        ayahCount: 40,
        isMakki: true,
        juzStart: 30),
    QuranSurah(
        number: 79,
        nameArabic: "النازعات",
        nameKurdish: "نازیعات",
        ayahCount: 46,
        isMakki: true,
        juzStart: 30),
    QuranSurah(
        number: 80,
        nameArabic: "عبس",
        nameKurdish: "عەبەسە",
        ayahCount: 42,
        isMakki: true,
        juzStart: 30),
    QuranSurah(
        number: 81,
        nameArabic: "التكوير",
        nameKurdish: "تەکویر",
        ayahCount: 29,
        isMakki: true,
        juzStart: 30),
    QuranSurah(
        number: 82,
        nameArabic: "الانفطار",
        nameKurdish: "ئینفیتار",
        ayahCount: 19,
        isMakki: true,
        juzStart: 30),
    QuranSurah(
        number: 83,
        nameArabic: "المطففين",
        nameKurdish: "موتەففیفین",
        ayahCount: 36,
        isMakki: true,
        juzStart: 30),
    QuranSurah(
        number: 84,
        nameArabic: "الانشقاق",
        nameKurdish: "ئینشیقاق",
        ayahCount: 25,
        isMakki: true,
        juzStart: 30),
    QuranSurah(
        number: 85,
        nameArabic: "البروج",
        nameKurdish: "بوروج",
        ayahCount: 22,
        isMakki: true,
        juzStart: 30),
    QuranSurah(
        number: 86,
        nameArabic: "الطارق",
        nameKurdish: "تاریق",
        ayahCount: 17,
        isMakki: true,
        juzStart: 30),
    QuranSurah(
        number: 87,
        nameArabic: "الأعلى",
        nameKurdish: "ئەعلا",
        ayahCount: 19,
        isMakki: true,
        juzStart: 30),
    QuranSurah(
        number: 88,
        nameArabic: "الغاشية",
        nameKurdish: "غاشیە",
        ayahCount: 26,
        isMakki: true,
        juzStart: 30),
    QuranSurah(
        number: 89,
        nameArabic: "الفجر",
        nameKurdish: "فەجر",
        ayahCount: 30,
        isMakki: true,
        juzStart: 30),
    QuranSurah(
        number: 90,
        nameArabic: "البلد",
        nameKurdish: "بەلەد",
        ayahCount: 20,
        isMakki: true,
        juzStart: 30),
    QuranSurah(
        number: 91,
        nameArabic: "الشمس",
        nameKurdish: "شەمس",
        ayahCount: 15,
        isMakki: true,
        juzStart: 30),
    QuranSurah(
        number: 92,
        nameArabic: "الليل",
        nameKurdish: "لەیل",
        ayahCount: 21,
        isMakki: true,
        juzStart: 30),
    QuranSurah(
        number: 93,
        nameArabic: "الضحى",
        nameKurdish: "ضوحا",
        ayahCount: 11,
        isMakki: true,
        juzStart: 30),
    QuranSurah(
        number: 94,
        nameArabic: "الشرح",
        nameKurdish: "شەرح",
        ayahCount: 8,
        isMakki: true,
        juzStart: 30),
    QuranSurah(
        number: 95,
        nameArabic: "التين",
        nameKurdish: "تین",
        ayahCount: 8,
        isMakki: true,
        juzStart: 30),
    QuranSurah(
        number: 96,
        nameArabic: "العلق",
        nameKurdish: "عەلەق",
        ayahCount: 19,
        isMakki: true,
        juzStart: 30),
    QuranSurah(
        number: 97,
        nameArabic: "القدر",
        nameKurdish: "قەدر",
        ayahCount: 5,
        isMakki: true,
        juzStart: 30),
    QuranSurah(
        number: 98,
        nameArabic: "البينة",
        nameKurdish: "بەییینە",
        ayahCount: 8,
        isMakki: false,
        juzStart: 30),
    QuranSurah(
        number: 99,
        nameArabic: "الزلزلة",
        nameKurdish: "زەلزەلە",
        ayahCount: 8,
        isMakki: false,
        juzStart: 30),
    QuranSurah(
        number: 100,
        nameArabic: "العاديات",
        nameKurdish: "عادیات",
        ayahCount: 11,
        isMakki: true,
        juzStart: 30),
    QuranSurah(
        number: 101,
        nameArabic: "القارعة",
        nameKurdish: "قارعە",
        ayahCount: 11,
        isMakki: true,
        juzStart: 30),
    QuranSurah(
        number: 102,
        nameArabic: "التكاثر",
        nameKurdish: "تەکاسور",
        ayahCount: 8,
        isMakki: true,
        juzStart: 30),
    QuranSurah(
        number: 103,
        nameArabic: "العصر",
        nameKurdish: "عەسر",
        ayahCount: 3,
        isMakki: true,
        juzStart: 30),
    QuranSurah(
        number: 104,
        nameArabic: "الهمزة",
        nameKurdish: "هومەزە",
        ayahCount: 9,
        isMakki: true,
        juzStart: 30),
    QuranSurah(
        number: 105,
        nameArabic: "الفيل",
        nameKurdish: "فیل",
        ayahCount: 5,
        isMakki: true,
        juzStart: 30),
    QuranSurah(
        number: 106,
        nameArabic: "قريش",
        nameKurdish: "قورەیش",
        ayahCount: 4,
        isMakki: true,
        juzStart: 30),
    QuranSurah(
        number: 107,
        nameArabic: "الماعون",
        nameKurdish: "ماعون",
        ayahCount: 7,
        isMakki: true,
        juzStart: 30),
    QuranSurah(
        number: 108,
        nameArabic: "الكوثر",
        nameKurdish: "کەوسەر",
        ayahCount: 3,
        isMakki: true,
        juzStart: 30),
    QuranSurah(
        number: 109,
        nameArabic: "الكافرون",
        nameKurdish: "کافیرون",
        ayahCount: 6,
        isMakki: true,
        juzStart: 30),
    QuranSurah(
        number: 110,
        nameArabic: "النصر",
        nameKurdish: "نەسر",
        ayahCount: 3,
        isMakki: false,
        juzStart: 30),
    QuranSurah(
        number: 111,
        nameArabic: "المسد",
        nameKurdish: "مەسەد",
        ayahCount: 5,
        isMakki: true,
        juzStart: 30),
    QuranSurah(
        number: 112,
        nameArabic: "الإخلاص",
        nameKurdish: "ئیخلاس",
        ayahCount: 4,
        isMakki: true,
        juzStart: 30),
    QuranSurah(
        number: 113,
        nameArabic: "الفلق",
        nameKurdish: "فەلەق",
        ayahCount: 5,
        isMakki: true,
        juzStart: 30),
    QuranSurah(
        number: 114,
        nameArabic: "الناس",
        nameKurdish: "ناس",
        ayahCount: 6,
        isMakki: true,
        juzStart: 30),
  ];
}
